# Generated by Django 4.2.4 on 2023-08-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_twitchuser_broadcaster_type_twitchuser_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitchuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
