# Generated by Django 4.2.4 on 2023-08-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_twitchuser_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="twitchuser",
            name="user_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="twitchuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
