# Generated by Django 4.2.4 on 2023-08-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_twitchuser_user_id_alter_twitchuser_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="twitchuser",
            old_name="user_id",
            new_name="twitch_id",
        ),
    ]
