# Generated by Django 4.2.4 on 2023-09-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
