# Generated by Django 4.2.4 on 2023-08-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_twitchuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TwitchUser",
        ),
    ]
