# Generated by Django 4.2.4 on 2023-08-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_viewer_alter_streamsession_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="submitted_by",
        ),
        migrations.AddField(
            model_name="video",
            name="viewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewer_videos",
                to="api.viewer",
            ),
        ),
    ]
