# Generated by Django 4.2.4 on 2023-08-13 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_video_submitted_by_video_viewer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamsession",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 13, 12, 19, 59, 872797)
            ),
        ),
    ]
